# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='blog/images/post/no.png', upload_to='blog/images/post/'),
        ),
    ]
