# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-15 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160915_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='blog/images/post/anonym.png', upload_to='blog/images/user/'),
        ),
    ]
