# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20160915_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='blog/images/anonym.jpg', null=True, upload_to='post/'),
        ),
    ]
